name: env_guard
description: A simple, robust, and typed environment validation library for Dart/Flutter, designed to simplify and secure environment in applications
version: 1.1.0
repository: https://github.com/LeadcodeDev/env_guard

environment:
  sdk: ^3.7.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
